services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      VITE_API_URL: ${VITE_API_URL}
    ports:
      - "3000:80"
    networks:
      - api-networks
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300mb

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:${API_PORT}"
    environment:
      PORT: ${API_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: curl -f http://127.0.0.1:${API_PORT}/api/data || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500mb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - api-networks
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - api-networks

networks:
  api-networks:

volumes:
  postgres-data:
