services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - api-networks
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300mb

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:${API_PORT}"
    environment:
      PORT: ${API_PORT}
    healthcheck:
      test: curl -f http://127.0.0.1:${API_PORT}/api/data || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500mb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - api-networks

networks:
  api-networks:
